'Solution'
mate-academy/py-documentation-and-tests pull request #38
Opened 2022-08-31 13:21 UTC by LaskoA

Please check my solution and help to fix failure related to "test_create_movie" in class AdminMovieAPITests.

Thank you.

2022-08-31 13:30 UTC, Abnormaltype requested changes

2022-08-31 13:30 UTC, Abnormaltype commented on cinema/views.py
> +                type={"type": "list", "items": {"type": "number"}},
the same here

2022-08-31 13:30 UTC, Abnormaltype commented on cinema/views.py
> +                type={"type": "list", "items": {"type": "number"}},
the saem here

2022-08-31 18:13 UTC, LaskoA commented
Please check now, thank you :)

2022-09-01 08:29 UTC, IvanRamyk approved these changes
Good job!

2022-09-01 12:16 UTC, Abnormaltype approved these changes

2022-09-01 12:17 UTC, closed without merging