Sol
mate-academy/py-documentation-and-tests pull request #573
Opened 2024-08-04 10:29 UTC by Unlie9

2024-08-06 09:46 UTC, MNDonut requested changes

2024-08-06 09:46 UTC, MNDonut commented on cinema_service/urls.py
> +         SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
actually swagger shouldn't be a part of any app, thus you have to remove cinema from the endpoints. it's the best practice how to access swagger for frontend developers

2024-08-06 09:46 UTC, MNDonut commented on user/views.py
>      permission_classes = (IsAuthenticated,)
you can remove this comment

2024-08-16 10:55 UTC, DevSpaciX approved these changes

2024-08-17 20:59 UTC, closed without merging